run sacct after pulling docker in github actions slurm test

diff --git a/.github/workflows/slurm-ci.yml b/.github/workflows/slurm-ci.yml
--- a/.github/workflows/slurm-ci.yml
+++ b/.github/workflows/slurm-ci.yml
@@ -24,10 +24,19 @@ jobs:
     - name: Pull docker image
       run: docker pull $DOCKER_IMAGE
     - name: Have image running in background
+      run: docker run `bash <(curl -s https://codecov.io/env)` -itd -h ernie --name slurm -v `pwd`:/pydra $DOCKER_IMAGE
+    - name: Display previous jobs with sacct
       run: |
-        docker run `bash <(curl -s https://codecov.io/env)` -itd -h ernie --name slurm -v `pwd`:/pydra $DOCKER_IMAGE
         echo "Allowing ports/daemons time to start" && sleep 10
-    #  uses: actions/setup-python@v2
+        docker exec slurm bash -c "sacctmgr -i add cluster name=linux \
+          && supervisorctl restart slurmdbd \
+          && supervisorctl restart slurmctld \
+          && sacctmgr -i add account none,test Cluster=linux Description='none' Organization='none'"
+        docker exec slurm bash -c "sacct && sinfo && squeue" 2&> /dev/null
+        if [ $? -ne 0 ]; then
+            echo "Slurm docker image error"
+            exit 1
+        fi
 
 
 # https://github.community/t/confused-with-runs-on-and-container-options/16258/2
